apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
      containers:
      - name: springbootapp
        image: arijknani/springbootapp:latest
        ports:
        - containerPort: 9090
        env:
        - name: SPRING_DATASOURCE_URL
          value: "mongodb://gte3:gte3@mongo-service:27017/gte3?authSource=admin&readPreference=primaryPreferred&directConnection=true"
---
apiVersion: v1
kind: Service
metadata:
  name: springbootapp-service
spec:
  selector:
    app: springbootapp
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
