version: "3"

services:
  spring-app:
    image: arijknani/springbootapp
    container_name: "springbootapp"
    ports:
      - 9090:9090
    networks:
      - mynetwork
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongo-service"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    volumes:
      - student-data:/data/db

volumes:
  student-data:

networks:
  mynetwork:
    driver: bridge

